const wait = () => new Promise(resolve => setTimeout(resolve, 80))
const check = (value: boolean, message: string) => { if (!value) throw new Error(message) }
const header = () => document.querySelector<HTMLButtonElement>('.settings-provider-identity')!
const input = () => document.querySelector<HTMLInputElement>('.settings-provider-input')!
const button = (label: string) => document.querySelector<HTMLButtonElement>('[aria-label="' + label + '"]')!
function type(value: string) {
  Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')!.set!.call(input(), value)
  input().dispatchEvent(new Event('input', { bubbles: true }))
}
export async function scenarios() {
  check(header().getAttribute('aria-expanded') === 'false', 'initially collapsed')
  check(!input(), 'no hidden key input in collapsed tab')
  button('OpenCode Go enabled').click()
  await wait()
  check(header().getAttribute('aria-expanded') === 'false', 'switch does not expand tab')
  check(button('OpenCode Go enabled').getAttribute('aria-checked') === 'false', 'switch updates')
  header().click()
  await wait()
  check(input().type === 'password', 'expanded field masks key')
  const card = document.querySelector('.settings-provider-row')!.getBoundingClientRect()
  const panel = document.querySelector('.settings-provider-key')!.getBoundingClientRect()
  check(Math.abs(card.left - panel.left) < 1 && Math.abs(card.right - panel.right) < 1, 'dropdown matches both card edges')
  check(Math.abs(card.bottom - panel.top) < 1, 'dropdown joins the card without overlap or a gap')
  check(document.getElementById(header().getAttribute('aria-controls')!)!.contains(input()), 'disclosure controls panel')
  type('reject')
  await wait()
  document.querySelector<HTMLButtonElement>('.settings-provider-save')!.click()
  await wait()
  check(input().value === 'reject', 'failed save preserves draft')
  type('test-key')
  await wait()
  button('Show key').click()
  await wait()
  check(input().type === 'text', 'show key works')
  header().click()
  await wait()
  header().click()
  await wait()
  check(input().type === 'password' && input().value === 'test-key', 'reopening masks retained draft')
  document.querySelector<HTMLButtonElement>('.settings-provider-save')!.click()
  await wait()
  check(input().value === '', 'successful save clears draft')
  check(!document.querySelector('.settings-provider-dot'), 'disabled provider has no green dot')
  button('OpenCode Go enabled').click()
  await wait()
  check(Boolean(document.querySelector('.settings-provider-logo .settings-provider-dot')), 'enabled provider with key has logo dot')
  check(!document.querySelector('.settings-provider-status, .settings-provider-check'), 'no status text or check mark')
  button('Remove key').click()
  await wait()
  check(!document.querySelector('[aria-label="Remove key"]'), 'removing key updates controls')
  check(!document.querySelector('.settings-provider-dot'), 'removing key clears green dot')
  check(document.documentElement.scrollWidth <= innerWidth, 'no horizontal overflow')
  return ['collapsed provider tabs', 'independent enable switch', 'accessible panel linkage', 'failed save recovery', 'key visibility and draft persistence', 'save and remove status', 'responsive layout']
}
